// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HourlyChartController from "./hourly_chart_controller"
application.register("hourly-chart", HourlyChartController)

import LocationSearchController from "./location_search_controller"
application.register("location-search", LocationSearchController)

import SideNavController from "./side_nav_controller"
application.register("side-nav", SideNavController)
